#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Generate a spec-map.md index from a .spec/ directory so the index never drifts
    from the folders/files on disk.

.DESCRIPTION
    Two layouts are supported:
      -Mode folders (default): each subdirectory of -SpecPath is an area. Primary file =
                               tasks.md, else the first *.md, else flagged evidence-only.
      -Mode files            : each *.md directly in -SpecPath is an area (nested-spec layout,
                               e.g. .spec/<project>/).

    Scope is taken from each file's first markdown heading. Status is a best-effort scan for a
    "Status:" line or common keywords (complete/shipped/done/open/planning/blocked); else "unknown".
    Re-run as part of close-the-loop. Use -DryRun to preview without writing.

.EXAMPLE
    pwsh ~/.ai-workflow/scripts/build-spec-map.ps1 -SpecPath .spec
.EXAMPLE
    pwsh ~/.ai-workflow/scripts/build-spec-map.ps1 -SpecPath .spec/ai-video-production-system -Mode files
#>
[CmdletBinding()]
param(
    [string]$SpecPath = ".spec",
    [ValidateSet("folders", "files")][string]$Mode = "folders",
    [string]$OutFile,
    [string]$Title,
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path $SpecPath)) { throw "SpecPath not found: $SpecPath" }
$specFull = (Resolve-Path $SpecPath).Path
if (-not $OutFile) { $OutFile = Join-Path $specFull "spec-map.md" }
if (-not $Title) { $Title = "$(Split-Path $specFull -Leaf) — Spec Map" }

function Get-Scope([string]$file) {
    if (-not (Test-Path $file)) { return "" }
    foreach ($line in Get-Content $file -TotalCount 40) {
        if ($line -match '^\s*#{1,3}\s+(.+?)\s*$') { return $Matches[1].Trim() }
    }
    return ""
}

function Format-Status([string]$s) {
    if (-not $s) { return "unknown" }
    $s = $s -replace '[*_`]', ''          # strip markdown emphasis
    $s = ($s -split "`n")[0].Trim()        # first line only
    $s = $s -replace '\s+', ' '            # collapse whitespace
    if ($s.Length -gt 40) { $s = $s.Substring(0, 37).TrimEnd() + "..." }
    if (-not $s) { return "unknown" }
    return $s
}

function Get-StatusHint([string]$file) {
    if (-not (Test-Path $file)) { return "evidence-only" }
    $head = (Get-Content $file -TotalCount 60) -join "`n"
    if ($head -match '(?im)^\s*[-*]?\s*\**status\**\s*[:：]\s*(.+?)\s*$') { return (Format-Status $Matches[1]) }
    foreach ($kw in @('superseded', 'shipped', 'complete', 'done', 'accepted', 'in progress', 'blocked', 'planning', 'draft', 'open')) {
        if ($head -match "(?i)\b$kw\b") { return $kw }
    }
    return "unknown"
}

# Collect areas
$rows = @()
if ($Mode -eq "folders") {
    $areas = Get-ChildItem -Path $specFull -Directory | Sort-Object Name
    foreach ($a in $areas) {
        $primary = Join-Path $a.FullName "tasks.md"
        if (-not (Test-Path $primary)) {
            $md = Get-ChildItem -Path $a.FullName -Filter *.md -File | Sort-Object Name | Select-Object -First 1
            $primary = if ($md) { $md.FullName } else { $null }
        }
        $rel = if ($primary) { ".spec/" + $a.Name + "/" + (Split-Path $primary -Leaf) } else { ".spec/" + $a.Name + "/ (no .md)" }
        $scope = if ($primary) { Get-Scope $primary } else { $a.Name }
        $status = if ($primary) { Get-StatusHint $primary } else { "evidence-only" }
        $rows += [pscustomobject]@{ Area = $a.Name; Spec = $rel; Scope = $scope; Status = $status }
    }
} else {
    $files = Get-ChildItem -Path $specFull -Filter *.md -File | Where-Object { $_.Name -ne "spec-map.md" } | Sort-Object Name
    foreach ($f in $files) {
        $rows += [pscustomobject]@{ Area = ($f.BaseName); Spec = $f.Name; Scope = (Get-Scope $f.FullName); Status = (Get-StatusHint $f.FullName) }
    }
}

if ($rows.Count -le 8 -and $Mode -eq "folders") {
    Write-Warning "Only $($rows.Count) areas found. A spec-map may be unnecessary (<= 8). current.md + tasks.md may be enough."
}

# Build markdown
$stamp = (Get-Date -Format "yyyy-MM-dd")
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("# $Title")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("> Generated by build-spec-map.ps1 on $stamp. Do not hand-edit — re-run the script.")
[void]$sb.AppendLine("> Living tier: re-generate at close-the-loop so it never drifts from disk.")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("| Area | Primary spec | Scope | Status |")
[void]$sb.AppendLine("| --- | --- | --- | --- |")
foreach ($r in $rows) {
    $scope = if ($r.Scope) { $r.Scope } else { "—" }
    [void]$sb.AppendLine("| $($r.Area) | ``$($r.Spec)`` | $scope | $($r.Status) |")
}
$out = $sb.ToString()

if ($DryRun) {
    Write-Host $out
    Write-Host "`n(dry-run: $($rows.Count) areas; would write to $OutFile)"
} else {
    Set-Content -Path $OutFile -Value $out -Encoding UTF8
    Write-Host "Wrote $($rows.Count) areas to $OutFile"
}
